### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

### ISSUE THREAD

**Issue by panovr** [lee-zq/VesselSeg-Pytorch#3]
```
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    main()
  File "train.py", line 71, in main
    val_log = val(val_loader,net,criterion,device)
  File "D:\Users\zhaoyili\project\VesselSeg-Pytorch\function.py", line 126, in val
    ('val_auc_roc', evaluater.auc_roc())])
  File "D:\Users\zhaoyili\project\VesselSeg-Pytorch\lib\metrics.py", line 44, in auc_roc
    AUC_ROC = roc_auc_score(self.target, self.output)
  File "D:\Users\zhaoyili\.conda\envs\pytorch\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "D:\Users\zhaoyili\.conda\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py", line 524, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "D:\Users\zhaoyili\.conda\envs\pytorch\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "D:\Users\zhaoyili\.conda\envs\pytorch\lib\site-packages\sklearn\utils\validation.py", line 720, in check_array
    _assert_all_finite(array,
  File "D:\Users\zhaoyili\.conda\envs\pytorch\lib\site-packages\sklearn\utils\validation.py", line 103, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
```

**Comment by lixiangcog** [comment]
我也遇到了这个问题 你解决了么

**Comment by SilverBach805** [comment]
我也遇到了这个问题，你们解决了吗

**Comment by liqiangde** [comment]
用Denseunet没这个问题，切换Unet模型训练7个epoch出现了这个问题

**Comment by Zhuxl123** [comment]
> 用Denseunet没这个问题，切换Unet模型训练7个epoch出现了这个问题

用unet训练了20epoch出现了这个问题，请问你解决了吗？
